# Generated by Django 5.0.2 on 2024-02-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["title"], name="article_art_title_d15895_idx"),
        ),
    ]
